# Generated by Django 5.0.1 on 2024-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
