# Generated by Django 5.0.1 on 2024-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bus_options_bus_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='bus',
            name='prebooked_seats',
            field=models.ManyToManyField(blank=True, related_name='prebooked_seats', to='app.seat'),
        ),
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.ManyToManyField(related_name='bus_seats', to='app.seat'),
        ),
    ]
