# Generated by Django 5.0.1 on 2024-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seat_remove_bus_seats_available_bus_prebooked_seats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AlterField(
            model_name='bus',
            name='prebooked_seats',
            field=models.ManyToManyField(blank=True, to='app.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(),
        ),
    ]
