# Generated by Django 5.0.1 on 2024-01-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_seat_options_remove_bus_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='prebooked_seats',
        ),
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bus'),
        ),
    ]
