# Generated by Django 5.0.1 on 2024-01-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bus_prebooked_seats_seat_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Pre Booked Seat', 'verbose_name_plural': 'Pre Booked Seats'},
        ),
    ]
