# Generated by Django 5.0.1 on 2024-01-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_seat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
