# Generated by Django 5.0.1 on 2024-01-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bus_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
