# Generated by Django 5.0.1 on 2024-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bus_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
